#include "mdisass.h"
#include "insn/mdisass-insn.h"

disass_insn one_byte_insn[] =
{
    { add_Eb_Gb },      // 0x00
    { add_Ev_Gv },      // 0x01
    { add_Gb_Eb },      // 0x02
    { add_Gv_Ev },      // 0x03
    { add_AL_Ib },      // 0x04
    { add_eAX_Iv },     // 0x05
    { push_ES },        // 0x06
    { pop_ES },         // 0x07
    { or_Eb_Gb },       // 0x08
    { or_Ev_Gv },       // 0x09
    { or_Gb_Eb },       // 0x0A
    { or_Gv_Ev },       // 0x0B
    { or_AL_Ib },       // 0x0C
    { or_eAX_Iv },      // 0x0D
    { push_CS },        // 0x0E
    { NULL },           // 0x0F
    { adc_Eb_Gb },      // 0x10
    { adc_Ev_Gv },      // 0x11
    { adc_Gb_Eb },      // 0x12
    { adc_Gv_Ev },      // 0x13
    { adc_AL_Ib },      // 0x14
    { adc_eAX_Iv },     // 0x15
    { push_SS },        // 0x16
    { pop_SS },         // 0x17
    { sbb_Eb_Gb },      // 0x18
    { sbb_Ev_Gv },      // 0x19
    { sbb_Gb_Eb },      // 0x1A
    { sbb_Gv_Ev },      // 0x1B
    { sbb_AL_Ib },      // 0x1C
    { sbb_eAX_Iv },     // 0x1D
    { push_DS },        // 0x1E
    { pop_DS },         // 0x1F
    { and_Eb_Gb },      // 0x20
    { and_Ev_Gv },      // 0x21
    { and_Gb_Eb },      // 0x22
    { and_Gv_Ev },      // 0x23
    { and_AL_Ib },      // 0x24
    { and_eAX_Iv },     // 0x25
    { NULL },           // 0x26
    { daa },            // 0x27
    { sub_Eb_Gb },      // 0x28
    { sub_Ev_Gv },      // 0x29
    { sub_Gb_Eb },      // 0x2A
    { sub_Gv_Ev },      // 0x2B
    { sub_AL_Ib },      // 0x2C
    { sub_eAX_Iv },     // 0x2D
    { NULL },           // 0x2E
    { das },            // 0x2F
    { xor_Eb_Gb },      // 0x30
    { xor_Ev_Gv },      // 0x31
    { xor_Gb_Eb },      // 0x32
    { xor_Gv_Ev },      // 0x33
    { xor_AL_Ib },      // 0x34
    { xor_eAX_Iv },     // 0x35
    { NULL },           // 0x36
    { aaa },            // 0x37
    { cmp_Eb_Gb },      // 0x38
    { cmp_Ev_Gv },      // 0x39
    { cmp_Gb_Eb },      // 0x3A
    { cmp_Gv_Ev },      // 0x3B
    { cmp_AL_Ib },      // 0x3C
    { cmp_eAX_Iv },     // 0x3D
    { NULL },           // 0x3E
    { aas },            // 0x3F
    { inc_eAX },        // 0x40
    { inc_eCX },        // 0x41
    { inc_eDX },        // 0x42
    { inc_eBX },        // 0x43
    { inc_eSP },        // 0x44
    { inc_eBP },        // 0x45
    { inc_eSI },        // 0x46
    { inc_eDI },        // 0x47
    { dec_eAX },        // 0x48
    { dec_eCX },        // 0x49
    { dec_eDX },        // 0x4A
    { dec_eBX },        // 0x4B
    { dec_eSP },        // 0x4C
    { dec_eBP },        // 0x4D
    { dec_eSI },        // 0x4E
    { dec_eDI },        // 0x4F
    { push_eAX },       // 0x50
    { push_eCX },       // 0x51
    { push_eDX },       // 0x52
    { push_eBX },       // 0x53
    { push_eSP },       // 0x54
    { push_eBP },       // 0x55
    { push_eSI },       // 0x56
    { push_eDI },       // 0x57
    { pop_eAX },        // 0x58
    { pop_eCX },        // 0x59
    { pop_eDX },        // 0x5A
    { pop_eBX },        // 0x5B
    { pop_eSP },        // 0x5C
    { pop_eBP },        // 0x5D
    { pop_eSI },        // 0x5E
    { pop_eDI },        // 0x5F
    { pusha },          // 0x60
    { popa },           // 0x61
    { bound },          // 0x62
};

